# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b4696f52a38118780bdcd7074012da44"
name = "remix-tutorial"
handle = "remix-tutorial-14"
application_url = "https://offline-compatibility-superb-marketing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dh-ogne.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://offline-compatibility-superb-marketing.trycloudflare.com/auth/callback",
  "https://offline-compatibility-superb-marketing.trycloudflare.com/auth/shopify/callback",
  "https://offline-compatibility-superb-marketing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
